name: final
provider: aws
create_rds: true
username: default
password: zenml
ingress_path: jayesh-test
database_ssl_verify_server_cert: false
create_ingress_controller: false
ingress_controller_hostname: ac8e6c63af207436194ab675ee71d85a-1399000870.us-east-1.elb.amazonaws.com
zenmlserver_image_tag: server-test-three

namespace: testcli

