name: Test Examples on Remote Infrastructure

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize ]
  issue_comment:
    types: [ created ]

jobs:
  check_comments:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request
    outputs:
      kf_trigger: ${{ steps.check.outputs.triggered }}
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: 'LTKF!'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: 'echo Found LTKF! in the comments!'
        if: steps.check.outputs.triggered == 'true'

  kubeflow-tests:
    # needs: check_comments
    # Run this one automatically if 'LTKF! is in the PR comments
    if: ${{ needs.check_comments.outputs.kf_trigger == 'true' }}
    uses: ./.github/workflows/kubeflow.yml
    secrets: inherit

  reply-on-pr:
    needs: kubeflow-tests
    runs-on: ubuntu-latest
    steps:
      - name: Message success
        if: ${{ success() }}
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Kubeflow tests succeeded! ✅',
            });
      - name: Message failure
        if: ${{ failure() }}
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Kubeflow tests failed! ❌',
            });