name: Kubeflow

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Use tmate session for debugging'
        required: false
        type: boolean
  workflow_call:

jobs:
  kubeflow_tests:
    name: kubeflow_tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      ZENML_DEBUG: 1
      ZENML_ANALYTICS_OPT_IN: false
      PYTHONIOENCODING: 'utf-8'

    steps:
      - uses: actions/checkout@v2

      # Workaround from FuseML (https://github.com/fuseml/fuseml/blob/main/.github/workflows/ci.yml)
      # as the TF images are too large for the GH action runner disk
      - name: Free disk space
        shell: bash
        run: |
          echo "Available storage:"
          df -h
          echo
          echo -n "  Removing: .NET (frees ~22GB)"
          sudo rm -rf /usr/share/dotnet
          echo "... done"
          echo
          echo "Available storage:"
          df -h

      - name: Install Linux System Dependencies
        if: runner.os=='Linux'
        run: sudo apt install graphviz

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::715803424590:role/limited_kubeflow_sandbox_tests_role
          role-session-name: Kubeflow_Test_Session
          aws-region: us-east-1

      - name: Setup environment with Poetry
        uses: ./.github/actions/setup_environment
        with:
          cache_version: ${{ secrets.GH_ACTIONS_CACHE_KEY }}

      - name: Install K3D and kubectl
        run: |
          curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          source $VENV
          zenml integration install kubeflow -y
          pip install notebook==6.4.11

      - name: Perform docker login and get Kubecontext
        run: bash scripts/setup_kubeflow_aws_connection.sh

      - name: Build docker image
        # this step can be much faster if we use an image that copies the
        # lockfile that was generated in the previous step
        run: docker build -t test-base-image:latest -f docker/base-test.Dockerfile .

      - name: Install Prerequisites
        run: |
          source $VENV
          zenml integration install s3 kubeflow evidently facets huggingface mlflow \
            tensorflow sklearn xgboost lightgbm slack neural_prophet deepchecks -f
      - name: Setup tmate session
        if: ${{ github.event.inputs.tags }}
        uses: mxschmitt/action-tmate@v3

      - name: Run tests
        env:
          TEST_MLFLOW_TRACKING_URI: https://ac8e6c63af207436194ab675ee71d85a-1399000870.us-east-1.elb.amazonaws.com
          TEST_MLFLOW_TRACKING_USERNAME: ${{ secrets.TEST_MLFLOW_TRACKING_USERNAME }}
          TEST_MLFLOW_TRACKING_PASSWORD: ${{ secrets.TEST_MLFLOW_TRACKING_PASSWORD }}
          TEST_SLACK_TOKEN: ${{ secrets.TEST_SLACK_TOKEN }}
          TEST_SLACK_CHANNEL_ID: ${{ secrets.TEST_SLACK_CHANNEL_ID }}
        run: |
          source $VENV
          pytest tests/integration/test_examples.py -s --on-kubeflow
