name: Kubeflow

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Use tmate session for debugging'
        required: false
        type: boolean
  workflow_call:

jobs:
  kubeflow_tests:
    name: kubeflow_tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      ZENML_DEBUG: 1
      ZENML_ANALYTICS_OPT_IN: false
      PYTHONIOENCODING: 'utf-8'

    steps:
      - uses: actions/checkout@v2

      - name: Install Linux System Dependencies
        if: runner.os=='Linux'
        run: sudo apt install graphviz

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::907999144431:role/limited_kubeflow_tests_role
          role-session-name: Kubeflow_Test_Session
          aws-region: us-east-1

      - name: Setup environment with Poetry
        uses: ./.github/actions/setup_environment
        with:
          cache_version: ${{ secrets.GH_ACTIONS_CACHE_KEY }}

      - name: Install K3D and kubectl
        run: |
          curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          source $VENV
          zenml integration install kubeflow -y

      - name: Perform docker login and get Kubecontext
        run: bash scripts/setup_kubeflow_aws_connection.sh

      - name: Build docker image
        # this step can be much faster if we use an image that copies the
        # lockfile that was generated in the previous step
        run: docker build -t test-base-image:latest -f docker/base-dev.Dockerfile .

      - name: Setup tmate session
        if: ${{ github.event.inputs.tags }}
        uses: mxschmitt/action-tmate@v3

      - name: Install Prerequisites
        run: |
          source $VENV
          zenml integration install mlflow s3 kubeflow -f

      - name: Run tests
        run: |
          source $VENV
          pytest tests/integration/test_examples.py -s --on-kubeflow --use-virtualenv
